version: 2
updates:
  - package-ecosystem: "npm"
    # server 
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    # client
    directory: "/client"
    schedule:
      interval: "daily"